{
  "sksl": {
    "entrypoint": "black_to_alpha_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float u_time;\nuniform float u_resolution_x;\nuniform float u_resolution_y;\n\nvec4 fragColor;\n\nvoid FLT_main()\n{\n    vec2 resolution = vec2(u_resolution_x, u_resolution_y);\n    vec2 uv = flutter_FragCoord.xy / resolution;\n    float strength = 0.20000000298023223876953125 + (0.800000011920928955078125 * sin(((u_time * 2.0) + (uv.x * 10.0)) + (uv.y * 10.0)));\n    vec3 color = mix(vec3(0.0), vec3(1.0), vec3(strength));\n    fragColor = vec4(color, strength);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_time",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "u_resolution_x",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "u_resolution_y",
        "rows": 1,
        "type": 10
      }
    ]
  }
}