{
  "sksl": {
    "entrypoint": "fire_scroll_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float u_time;\nuniform float u_scroll;\nuniform vec2 u_resolution;\n\nvec4 fragColor;\n\nfloat FLT_flutter_local_fire(inout vec2 uv)\n{\n    uv.y += (u_time * 0.1500000059604644775390625);\n    float strength = 0.100000001490116119384765625;\n    float n = (sin((uv.x * 10.0) + u_time) * 0.5) + (cos((uv.y * 20.0) + (u_time * 1.5)) * 0.5);\n    return smoothstep(0.300000011920928955078125, 0.800000011920928955078125, fract(n));\n}\n\nvoid FLT_main()\n{\n    vec2 uv_1 = flutter_FragCoord.xy / u_resolution;\n    vec2 param = uv_1 + vec2(0.0, u_scroll / u_resolution.y);\n    float _78 = FLT_flutter_local_fire(param);\n    float flame = _78;\n    vec3 color = mix(vec3(0.100000001490116119384765625, 0.0, 0.0), vec3(1.0, 0.5, 0.0), vec3(flame));\n    fragColor = vec4(color, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_time",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "u_scroll",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "u_resolution",
        "rows": 2,
        "type": 10
      }
    ]
  }
}