{
  "sksl": {
    "entrypoint": "masked_scroll_noise_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float u_time;\nuniform float u_scroll;\nuniform vec2 u_resolution;\nuniform float u_alphaToggle;\nuniform shader u_logo;\nuniform half2 u_logo_size;\n\nvec4 fragColor;\n\nfloat FLT_flutter_local_random(vec2 st)\n{\n    return fract(sin(dot(st, vec2(12.98980045318603515625, 78.233001708984375))) * 43758.546875);\n}\n\nfloat FLT_flutter_local_noise(vec2 st)\n{\n    vec2 i = floor(st);\n    vec2 f = fract(st);\n    vec2 param = i;\n    float a = FLT_flutter_local_random(param);\n    vec2 param_1 = i + vec2(1.0, 0.0);\n    float b = FLT_flutter_local_random(param_1);\n    vec2 param_2 = i + vec2(0.0, 1.0);\n    float c = FLT_flutter_local_random(param_2);\n    vec2 param_3 = i + vec2(1.0);\n    float d = FLT_flutter_local_random(param_3);\n    vec2 u = (f * f) * (vec2(3.0) - (f * 2.0));\n    return (mix(a, b, u.x) + (((c - a) * u.y) * (1.0 - u.x))) + (((d - b) * u.x) * u.y);\n}\n\nvoid FLT_main()\n{\n    vec2 uv = flutter_FragCoord.xy / u_resolution;\n    vec2 logoUV = uv;\n    logoUV.y += ((u_scroll / u_resolution.y) * 0.300000011920928955078125);\n    vec2 param_4 = (uv * 10.0) + vec2(0.0, u_time * 0.5);\n    float n = FLT_flutter_local_noise(param_4);\n    float mask = smoothstep(0.20000000298023223876953125, 0.60000002384185791015625, n);\n    vec4 logoColor = u_logo.eval(u_logo_size * ( logoUV));\n    float alpha = logoColor.w * mask;\n    float fade = smoothstep(0.0, 1.0, u_alphaToggle);\n    fragColor = vec4(logoColor.xyz * n, alpha * fade);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_time",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "u_scroll",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "u_resolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "u_alphaToggle",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 4,
        "name": "u_logo",
        "rows": 1,
        "type": 12
      }
    ]
  }
}