{
  "sksl": {
    "entrypoint": "scroll_noise_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float u_time;\nuniform vec2 u_resolution;\nuniform float u_scroll;\n\nvec4 fragColor;\n\nfloat FLT_flutter_local_noise(vec2 p)\n{\n    return fract(sin(dot(p, vec2(127.09999847412109375, 311.70001220703125))) * 43758.546875);\n}\n\nvoid FLT_main()\n{\n    vec2 uv = flutter_FragCoord.xy / u_resolution;\n    float scrollMod = u_scroll * 2.0;\n    vec2 param = (uv * 10.0) + vec2(u_time, scrollMod);\n    float n = FLT_flutter_local_noise(param);\n    vec3 color = vec3(n);\n    fragColor = vec4(color, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_time",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "u_resolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "u_scroll",
        "rows": 1,
        "type": 10
      }
    ]
  }
}